language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew assemble
  - ./gradlew check
  - [ "$(git branch | grep '*' | cut -d' ' -f2)" = 'master' ] && (npm install -g serverless && serverless deploy) || true
notifications:
  email: false
