service: learn-java

frameworkVersion: "=1.11.0"

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/learn-java.zip

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http:
          path: api/{proxy+}
          method: any

resources:
  Resources:
    edges:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: edges
        AttributeDefinitions:
          - AttributeName: graphName
            AttributeType: S
        KeySchema:
          - AttributeName: graphName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
