service: learn-java

frameworkVersion: "=1.12.0"

custom:
  defaultStage: dev
  defaultRegion: us-east-1

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/edges-${self:provider.stage}"]]

package:
  artifact: build/distributions/learn-java.zip

functions:
  all:
    handler: com.sharpandrew.learnjava.Handler
    events:
      - http:
          path: api/{proxy+}
          method: any

resources:
  Resources:
    edges:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: edges-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: edgeId
            AttributeType: S
        KeySchema:
          - AttributeName: edgeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
